SET client_encoding TO 'UTF8';

ALTER TABLE XHB_DISP_MGR_CDU DISABLE TRIGGER ALL;
ALTER TABLE XHB_DISP_MGR_COURT_SITE DISABLE TRIGGER ALL;
ALTER TABLE XHB_DISP_MGR_LOCAL_PROXY DISABLE TRIGGER ALL;
ALTER TABLE XHB_DISP_MGR_LOG DISABLE TRIGGER ALL;
ALTER TABLE XHB_DISP_MGR_MAPPING DISABLE TRIGGER ALL;
ALTER TABLE XHB_DISP_MGR_PROPERTY DISABLE TRIGGER ALL;
ALTER TABLE XHB_DISP_MGR_SCHEDULE DISABLE TRIGGER ALL;
ALTER TABLE XHB_DISP_MGR_SERVICE_AUDIT DISABLE TRIGGER ALL;
ALTER TABLE XHB_DISP_MGR_URL DISABLE TRIGGER ALL;
ALTER TABLE XHB_DISP_MGR_USER_DETAILS DISABLE TRIGGER ALL;
