SET client_encoding TO 'UTF8';

ALTER TABLE XHB_DISP_MGR_CDU ENABLE TRIGGER ALL;
ALTER TABLE XHB_DISP_MGR_COURT_SITE ENABLE TRIGGER ALL;
ALTER TABLE XHB_DISP_MGR_LOCAL_PROXY ENABLE TRIGGER ALL;
ALTER TABLE XHB_DISP_MGR_LOG ENABLE TRIGGER ALL;
ALTER TABLE XHB_DISP_MGR_MAPPING ENABLE TRIGGER ALL;
ALTER TABLE XHB_DISP_MGR_PROPERTY ENABLE TRIGGER ALL;
ALTER TABLE XHB_DISP_MGR_SCHEDULE ENABLE TRIGGER ALL;
ALTER TABLE XHB_DISP_MGR_SERVICE_AUDIT ENABLE TRIGGER ALL;
ALTER TABLE XHB_DISP_MGR_URL ENABLE TRIGGER ALL;
ALTER TABLE XHB_DISP_MGR_USER_DETAILS ENABLE TRIGGER ALL;
