SET client_encoding TO 'UTF8';

CREATE SEQUENCE dm_cdu_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 1;
CREATE SEQUENCE dm_court_site_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 1;
CREATE SEQUENCE dm_local_proxy_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 1;
CREATE SEQUENCE dm_log_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 1;
CREATE SEQUENCE dm_property_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 1;
CREATE SEQUENCE dm_schedule_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 1;
CREATE SEQUENCE dm_service_audit_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 1;
CREATE SEQUENCE dm_url_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 1;
CREATE SEQUENCE dm_user_details_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 1;
